version: 2
updates:
- package-ecosystem: maven
  directory: "/core"
  schedule:
    interval: "weekly"
- package-ecosystem: maven
  directory: "/examples"
  schedule:
    interval: "weekly"
- package-ecosystem: maven
  directory: "/reflection"
  schedule:
    interval: "weekly"
  # Ignore the version, because it is only used for testing
  ignore:
  - dependency-name: "one.microstream:microstream-storage-embedded"
  - dependency-name: "one.microstream:microstream-storage-configuration"
- package-ecosystem: maven
  directory: "/microstream-v5"
  schedule:
    interval: "weekly"
  # Ignore the version, because this is supposed to be for old MicroStream versions
  ignore:
  - dependency-name: "one.microstream:microstream-storage-embedded"
  - dependency-name: "one.microstream:microstream-storage-configuration"
- package-ecosystem: maven
  directory: "/microstream-v6"
  schedule:
    interval: "weekly"
  # Ignore the version, because this is supposed to be for old MicroStream versions
  ignore:
  - dependency-name: "one.microstream:microstream-storage-embedded"
  - dependency-name: "one.microstream:microstream-storage-configuration"
- package-ecosystem: maven
  directory: "/microstream-v7"
  schedule:
    interval: "weekly"